out_dir: results
metric_best: accuracy # originally: mae
metric_agg: argmin
wandb:
  use: True
  project: TrustHubDFG
dataset:
  format: PyG-TrustHubDFG #custom for TrustHub
  name: val[xtea].test[xtea] #custom for TrustHub
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+LapPE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
