out_dir: results
metric_best: accuracy # originally: mae
metric_agg: argmin
wandb:
  use: True
  project: TrustHubDFG
dataset:
  format: PyG-TrustHubDFG #custom for TrustHub
  name: val[xtea].test[xtea] #custom for TrustHub
  task: graph
  task_type: classification
  transductive: True
  split_mode: standard
  node_encoder: False
#  node_encoder_name: LinearNode+GraphormerBias
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_bn: False

train:
  mode: custom
  sampler: full_batch
#  sampler: saint_rw
#  batch_size: 32
  eval_period: 1
  enable_ckpt: False
#  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy


optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 20
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
